"""Per-connection state for the discovery tools (design/developers/impl_plan.md
Phase 2): what's been tried, what was found, and whether the fallback tier
order has actually been followed. One instance per connection/session -- see
run_unified_runtime.py's ``_resolve_tool_set``/``_make_dispatch``, which
construct a fresh ledger every time the dispatch factory is called, so one
user's evidence can never satisfy another's "credible source" check.

Tier order is: store first (recommend-and-stop) -> web search (native
Claude or Brave/Tavily fallback, see run_unified_runtime.py), with any
GitHub-domain result license-vetted wherever it surfaces (search_result_
enrichment.classify_and_record), -> asking the customer for URLs as a last
resort. ``search_github_plugins`` is no longer a mandatory step before web
search (it used to be -- see git history for why that was dropped: a
Claude-native web search call is a server-side tool our dispatch layer
never sees, so a "call GitHub first" sequencing rule can't be enforced once
that path exists; classifying every result by URL, regardless of which tool
produced it, applies uniformly instead). ``github_tried``/
``github_query_count`` remain purely as ``search_github_plugins``'s own
cap/attempt bookkeeping, not a gate on anything else.

This module has no knowledge of HTTP, GitHub, or any search provider; it's
just the bookkeeping the discovery handlers (handlers/discovery.py,
search_result_enrichment.py) all share.
"""

from __future__ import annotations

from dataclasses import dataclass, field
from datetime import datetime, timezone
from typing import Any


@dataclass
class EvidenceLedger:
    """Tracks fallback-tier progress and the evidence gathered so far for one
    plugin-authoring session.

    ``web_search_available`` is set once at construction from whether a
    search engine *and* its key were both configured for this run (see
    ``_resolve_tool_set``) -- it's not about whether a search has succeeded,
    only whether the tier exists at all this session. ``can_ask_for_urls``
    uses it to treat "the web-search tier doesn't exist" the same as "the
    web-search tier was tried" when deciding if asking the user for URLs is
    reasonable yet.
    """

    web_search_available: bool = False

    store_checked: bool = False
    github_tried: bool = False
    web_search_tried: bool = False

    sources: list[dict[str, Any]] = field(default_factory=list)

    github_query_count: int = 0
    web_search_query_count: int = 0
    fetch_count: int = 0
    license_lookup_count: int = 0

    def record_source(
        self,
        *,
        tier: str,
        url: str | None = None,
        title: str | None = None,
        license: str | None = None,  # noqa: A002 - matches the domain term
        license_ok: bool | None = None,
        note: str | None = None,
    ) -> dict[str, Any]:
        """Append one evidence entry and return it (so a handler can include
        it verbatim in its own return value without re-deriving the shape)."""
        entry = {
            "tier": tier,
            "url": url,
            "title": title,
            "license": license,
            "license_ok": license_ok,
            "note": note,
            "fetched_at": datetime.now(timezone.utc).isoformat(),
        }
        self.sources.append(entry)
        return entry

    def can_ask_for_urls(self) -> bool:
        """The ask-for-URLs step is only reasonable once web search has
        either been tried this session or was never available to try in
        the first place (``web_search_available`` reflects native-or-
        fallback availability, see run_unified_runtime.py)."""
        return self.web_search_tried or not self.web_search_available

    def has_evidence(self) -> bool:
        """Phase 3's generate_plugin_scaffold calls this before writing
        anything -- an empty ledger means refuse and create no files."""
        return bool(self.sources)


_SOURCES_MD_HEADER = (
    "# Sources\n\n"
    "Generated by plugin_authoring -- do not edit by hand. Every `generate_plugin_scaffold` "
    "call merges this session's newly gathered evidence into this file: a new source (by URL, "
    "or by title when a source has no URL) is appended; one already present is left alone, "
    "never duplicated or reordered. Check here first before issuing a fresh search for this "
    "plugin -- avoids re-researching the same thing across sessions.\n\n"
    "| Tier | Title | URL | License | License OK | Note | Fetched At |\n"
    "|---|---|---|---|---|---|---|\n"
)


def _source_identity(source: dict[str, Any]) -> str:
    """The key two sources are considered "the same" by -- URL when either
    has one (the common case), title otherwise. A source with neither has
    no identity to dedupe against, so it's always treated as new."""
    return (source.get("url") or source.get("title") or "").strip().lower()


def merge_sources(existing: list[dict[str, Any]], new: list[dict[str, Any]]) -> list[dict[str, Any]]:
    """*existing* (parsed from a prior ``sources.md``) with *new* (this
    session's ``EvidenceLedger.sources``) merged in -- append-only: a
    *new* entry whose identity (``_source_identity``) has zero
    intersection with anything in *existing* is added; one that already
    matches an existing entry is skipped, never replacing or reordering
    what's already on record."""
    merged = list(existing)
    seen = {_source_identity(s) for s in existing if _source_identity(s)}
    for source in new:
        identity = _source_identity(source)
        if identity and identity in seen:
            continue
        merged.append(source)
        if identity:
            seen.add(identity)
    return merged


def _escape_cell(value: str | None) -> str:
    """Pipes would break the table's column boundaries; embedded newlines
    (more likely in a search-result ``note``/snippet than in a title or
    URL) would break the one-row-per-line format entirely."""
    return (value or "").replace("|", "/").replace("\n", " ")


def render_sources_md(sources: list[dict[str, Any]]) -> str:
    """The full ``sources.md`` content for *sources* -- a markdown table,
    one row per source, in the order they were first recorded."""
    lines = [_SOURCES_MD_HEADER]
    for source in sources:
        title = _escape_cell(source.get("title"))
        url = _escape_cell(source.get("url"))
        license_ = _escape_cell(source.get("license"))
        note = _escape_cell(source.get("note"))
        license_ok = source.get("license_ok")
        license_ok_cell = "" if license_ok is None else str(bool(license_ok)).lower()
        fetched_at = source.get("fetched_at") or ""
        lines.append(
            f"| {source.get('tier') or ''} | {title} | {url} | {license_} | {license_ok_cell} | {note} | {fetched_at} |\n"
        )
    return "".join(lines)


def parse_sources_md(text: str) -> list[dict[str, Any]]:
    """The inverse of ``render_sources_md`` -- tolerant of the file not
    existing yet (callers pass ``""`` for that case) or of a stray
    non-table line; only well-formed ``| a | b | c | d | e | f | g |`` rows
    with exactly 7 cells, excluding the header and its ``---`` separator,
    become source dicts."""
    sources: list[dict[str, Any]] = []
    for line in text.splitlines():
        line = line.strip()
        if not (line.startswith("|") and line.endswith("|")):
            continue
        cells = [cell.strip() for cell in line.strip("|").split("|")]
        if len(cells) != 7:
            continue
        tier, title, url, license_, license_ok_cell, note, fetched_at = cells
        if tier.lower() == "tier" or set(tier) <= {"-"}:
            continue
        sources.append(
            {
                "tier": tier or None,
                "title": title or None,
                "url": url or None,
                "license": license_ or None,
                "license_ok": {"true": True, "false": False}.get(license_ok_cell.lower()),
                "note": note or None,
                "fetched_at": fetched_at or None,
            }
        )
    return sources
